### ISSUE TITLE
Publish a new version with `ldap_auto_bind` configuration to pypi

### ISSUE THREAD

**Issue by eumikhailov** [cea-sec/gmsad#10]
@vruello, hi!

Thank You for gmsad service!
We are tried to use [gmsad from pypi](https://pypi.org/project/gmsad/) and got error
```
ldap3.core.exceptions.LDAPBindError: automatic bind not successful - strongerAuthRequired
```

Actual source version has configuration parameter `ldap_auto_bind`, which may be set to `AUTO_BIND_TLS_BEFORE_BIND` for solving issue.

Can You publish a new version of package to pypi?

**Comment by vruello** [comment]
Hi! Yes, of course. I'll do it asap.

**Comment by vruello** [comment]
Version v0.2.0 has been released on Pypi!

**Comment by eumikhailov** [comment]
Thank you!
